---
title: "The Day and Night Perfect"
author: "admin"
date: "2025-05-03"
output: html_document
---

🇯🇵 Japan Ground Self-Defense Forces 🇯🇵
ㅤ
The Japan Ground Self-Defense Forces was established in 1954 under Article 9 of the Constitution, which was enacted after Japan's defeat in World War II. As a result, it is restricted from using war to resolve disputes between states. Japan can only maintain the Self-Defense Forces, which are responsible for protecting Japan's sovereignty and stability, and cannot conduct military offensives. Their duty is only to defend against threats that may come to Japan.

What we offer
An active and supportive group
Weekly activities
Experienced leaders and combat instructors
Unique Events

Recruitment Qualifications
be 13+
Loyalty to the Japan Self-Defense Forces
Have a positive attitude with willingness
Play on Computer
Be a person who has manners and that has respect for everyone

Structure
Japan Ground Self-Defense Force JGSDF
12th Brigade
48th infantry regiment
12th Helicopter Squadron
12th Reconnaissance Combat Battalion
12th Logistical Support Corps


>
(Note: Maritime and Air Self-Defense Forces are temporarily closed. There are plans to reopen in the future.)

📄 Expectations within the force 📄
Ability to understand and use basic English
Maturity and responsibility during activities and in the group

https://discord.gg/UMx39AQPQv
https://www.roblox.com/communities/16098456/JPN-Japan-Self-Defense-F-rces#!/about
https://www.roblox.com/communities/33892576/JPN-Japan-Ground-Self-Defence-Force#!/about
propaganda_ee2.png
RobloxScreenShot20250302_162559869.png